#!/usr/bin/env zsh
CHOME=$HOME/.my_config
BINPATH=$CHOME/installer

function printModuleUsage() {
    echo "Usage: cdot ${1} PROGRAM [ARGS]"
    echo "Avaliable Modules:"
    for file in ${@:2}; do
        echo $file:t:r
    done
}

function buildCompletion() {
    local -a list
    for file in $@; do
        list+=$file:r:t
    done
    echo $list
}

if [[  $# -lt 1  ]]; then
    echo "Usage: cdot subcommand [PROGRAM] [args]"
    echo "Avaliable Commands:"
    cmds=("install" "utils" "update" "zinit" "zreset")
    echo ${(j:\n:)cmds}
    exit 1
fi

case ${1} in
    install)
        if [[  $# -lt 2  ]]; then
            printModuleUsage "install" $BINPATH/script/*(*)
            exit 1
        fi

        if [[ ${2} = "_COMP" ]]; then
            buildCompletion $BINPATH/script/*(*)
            exit 0
        fi

        prog=($BINPATH/script/${2}.*(*))
        if [[ ! -f $prog ]]; then
            echo "Program: ${2} not found."
            exit 127
        fi
        $prog ${@:3}
    ;;
    utils)
        if [[  $# -lt 2  ]]; then
            printModuleUsage "utils" $BINPATH/utils/*(*)
            exit 1
        fi

        if [[ ${2} = "_COMP" ]]; then
            buildCompletion $BINPATH/utils/*(*)
            exit 0
        fi

        prog=($BINPATH/utils/${2}.*(*))
        if [[ ! -f $prog ]]; then
            echo "Program: ${2} not found."
            exit 127
        fi
        $prog ${@:3}
    ;;
    update)
        $BINPATH/run_update.sh
    ;;
    zinit)
        $CHOME/zgen_init.sh
    ;;
    zreset)
        $CHOME/zgen_init.sh reset ${2}
    ;;
    _COMP)
        cmds=(
            "zinit:Init ZSH"
            "zreset:Reset ZSH"
            "update:Update dotfiles"
            "install:Install Binary"
            "utils:Run utils tools"
            )
        echo ${(j:\n:)cmds}
        exit 0
    ;;
esac


exit $?
# if [[ ${1} = "utils" ]]; then
#     #BINPATH/${2} ${@:2}
#     echo BINPATH/${2} ${@:3}
# else [[  ]]
# # elif [[ ${1} = "update" ]]; then
# #     zgen-check-update
# # else
# #     zgen-install-plugin
# fi