#!/bin/bash

 command -v fzf >/dev/null 2>&1 || { echo "Fzf not found."; exit 1; }

(date; ps aux) |
  fzf --bind='ctrl-r:reload(date; ps aux)' \
      --header=$'Press CTRL-R to reload\n\n' --header-lines=2 \
      --preview='echo {}' --preview-window=down,3,wrap \
      --layout=reverse --height=80% | awk '{print $2}' | xargs kill -9